### ISSUE TITLE
Should we have a separate package.json for the library vs the lambda?

### ISSUE THREAD

**Issue by chee** [Financial-Times/runbook.md#5]
The library itself is quite small with no build step and few dependencies.

Would it be worth keeping this as a separate package that the lambda depends on, rather than having them both share the same package JSON?

The lambda has a build step and a number of dependencies that aren't needed by the small library that could be published on its own and consumed by things other than the lambda.

**Comment by GeoffThorpeFT** [comment]
I did wonder the same thing myself. runbook.md.parser and runbook.md.import.

**Comment by wheresrhys** [comment]
I go with the origami philosophy when it comes to componentisation, that having multiple use cases is a prerequisite to breaking something out into a component. We have lots of ideas of things we could build on top of the library, but IIRC the things we're most likely to build next (e.g. github app) are most likely gonna call the API/be part of the API.

Is it ok to just be disciplined and keep the lib in a separate directory for now (can even put the tests in there too?) so that when we need it to exist as a separate component for some feature we're building, it'll be relatively easy to split it out.

**Comment by doramatadora** [comment]
I think this codebase could be improved in terms of separation of concerns and reusability. Given that publishing a separate component is not a very involved change (and it would actually be helpful to not have it all run through webpack; separate dependency lists are nice too, I personally feel more motivated to keep them green), I think we should just go for it.

**Comment by chee** [comment]
#23
